[env:uiapduino_distance]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = genericCH32V003F4P6
framework = ch32v003fun
monitor_speed = 115200
lib_compat_mode = off
lib_deps =
  https://github.com/pololu/vl53l0x-arduino.git
  https://github.com/pololu/vl53l1x-arduino.git
build_flags =
  -std=gnu++17
  -Os
  -Iinclude
  -Ilib/ArduinoCompat/src
  -DFUNCONF_SUPPORT_CONSTRUCTORS=1
  -DSENSOR_VL53L1X
  -DHEATMAP_GRID_8
  ;-DLCD_BRINGUP_STAGE=4
  ; -DSENSOR_VL53L0X
  ; -DHEATMAP_GRID_16
  ; -DLCD_BRINGUP_STAGE=1
  ; -DLCD_BRINGUP_STAGE=3
  ; -DLCD_BRINGUP_STAGE=4
